; This file can be edited to change the style of the application
; Read "Qt Quick Controls 2 Configuration File" for details:
; https://doc.qt.io/qt-6/qtquickcontrols-configuration.html

[Controls]
Style=Material

[Material]
Theme=Dark
Accent=#CA2031
Primary=#000000
Background=#000000
Foreground=#E3E3E3
